apiVersion: v1
kind: Service
metadata:
  name: chaos
  labels:
    app.kubernetes.io/name: chaos
    app.kubernetes.io/part-of: heliantheon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chaos
  ports:
    - name: http
      port: 18000
      targetPort: http

