apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: chaos-config
    files:
      - config.toml=config.toml.tpl
generatorOptions:
  disableNameSuffixHash: true
